name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /www/wwwroot/docs/docs
        remote_host: 49.233.159.171
        remote_user: root
        remote_key: ${{ secrets.SSH_TOKEN }}
